### ISSUE TITLE
Windows Server 2012 RC Datacenter Issue

### ISSUE THREAD

**Issue by caryyu** [luodaoyi/kms-server#5]
我使用域名的简单方式激活成功之后（系统显示是已经激活状态），但是桌面上面依然会显示 License valid for 180 days，这个会有影响吗？

**Comment by luodaoyi** [comment]
没影响 因为180会自动激活一次

**Comment by Z841973620** [comment]
> 我使用域名的简单方式激活成功之后（系统显示是已经激活状态），但是桌面上面依然会显示 License valid for 180 days，这个会有影响吗？

你好，请问你有 Windows Server 2012 RC Datacenter 的 KMS 密钥吗？我的版本是 8400，公开的 Retail 密钥和正式版 9600 的 KMS 密钥都无法使用。
